# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]
