# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_partner',
            new_name='connected_partner',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_partner',
            new_name='connected_partner',
        ),
    ]
