# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='distributer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='partner.Distributer'),
            preserve_default=False,
        ),
    ]
