# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_retailer_distributer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='distributer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributer', to='partner.Distributer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to='partner.Retailer'),
        ),
    ]
