# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 08:27
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20171211_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='permissions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sell_product', 'Sell Product'), ('add_product', 'Add Product'), ('add_partner', 'Add Partner')], max_length=3),
        ),
    ]
