# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20171109_1046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distributer',
            new_name='Distributor',
        ),
        migrations.RenameField(
            model_name='connectedretailer',
            old_name='distributer',
            new_name='distributor',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='distributer',
            new_name='distributor',
        ),
        migrations.RenameField(
            model_name='retailer',
            old_name='distributer',
            new_name='distributor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='distributer',
        ),
        migrations.AddField(
            model_name='order',
            name='distributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='distributor', to='partner.Distributor'),
            preserve_default=False,
        ),
    ]
