# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='requested_delivery_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
