# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0003_auto_20171212_2030'),
    ]

