# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20171212_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='permissions',
            field=models.CharField(blank=True, choices=[('sell_product', 'Sell Product'), ('add_product', 'Add Product'), ('add_partner', 'Add Partner')], max_length=255),
        ),
    ]
