# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20171115_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
