# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseproduct',
            options={'verbose_name_plural': 'Product Master'},
        ),
    ]
