# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20171217_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='c_gst_total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='other_charge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='s_gst_total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
