# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_order_invoice_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Invoices'},
        ),
        migrations.AddField(
            model_name='product',
            name='c_gst',
            field=models.CharField(choices=[(0, '0'), (5, '5'), (12, '12'), (18, '18'), (28, '28')], default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='s_gst',
            field=models.CharField(choices=[(0, '0'), (5, '5'), (12, '12'), (18, '18'), (28, '28')], default=0, max_length=2),
        ),
    ]
