# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20171212_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
