# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_order_connected_partner'),
    ]