# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 10:42
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20171212_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
