# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20171125_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
