# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20171213_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Invoices'},
        ),
    ]
