# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_auto_20171125_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
