# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_auto_20171203_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to='partner.Retailer'),
        ),
    ]
