# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_auto_20171204_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='retailer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to='partner.Retailer'),
            preserve_default=False,
        ),
    ]
