# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_auto_20171203_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connecteddistributor',
            name='distributor',
        ),
        migrations.DeleteModel(
            name='ConnectedDistributor',
        ),
    ]
