# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('partner', '0015_extendeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
